auth0:
  audience: https://blue-bird.eu.auth0.com/api/v2/
spring:
  data:
    mongodb:
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://blue-bird.eu.auth0.com/